### ISSUE TITLE
ClamTk doesn't work. The GUI is never responsive.

### ISSUE THREAD

**Issue by dzu181** [dave-theunsub/clamtk#64] opened 2016-09-18 18:12 UTC
I installed ClamTk on Ubuntu 16.04 LTS and the GUI is not responsive , no matter what I do. Many people are also having this issue. 

Please fox this.
Thank you.

**Comment by dave-theunsub** [comment] 2016-09-18 18:16
Hi,

Can you give me some more information?   What version of clamtk are you using?  When did this start happening?

Also, please open a terminal window and type "clamtk" (no quotes). Then try to scan like you were doing.  If there are any error messages, please let me know.

respectfully
Dave M

**Comment by dzu181** [comment] 2016-09-19 03:35
I am using version 5.22.1-1 just like in the attached screenshot, Sir.
I downloaded it from this link:
https://bitbucket.org/dave_theunsub/clamtk/downloads/clamtk_5.22-1_all.deb

It happeded right at the first time I launched the Tk, and many many
times after I restarted my computer and the program itself, nothing
changed.
I tried to single click, double click, and even pressed the Enter key,
but nothing changed on the screen. Actually I saw no effects on the
screen, not a single pixel of my screen changed its state, despite the
color changes of the buttons I clicked on, like in the attached
screenshot. I also opened the Ubuntu Software Center on my Ubuntu
16.04 again, and I saw people commenting things about the same issue
on other versions of Clamtk as well. There were only complains, and no
solution. It seems that all versions got stuck at something, Sir.

I started the terminal and typed "clamtk" with no quotes, and nothing
changed. Still the same GUI, and the same non-responsive state.

I am looking forward to hearing from you.

Thank you.

Respectfully,
Dzu N





2016-09-19 1:16 GMT+07:00, Dave M <notifications@github.com>:

**Comment by dave-theunsub** [comment] 2016-09-19 08:48
This is weird.  I have Virtualbox with Ubuntu 16, 15, and 12.04, and this doesn't happen with any of them.  Or Fedora or CentOS either.

Do you remember what version worked last?  I'm trying to pinpoint when something may have happened... may help us figure out what's going on.

respectfully
Dave M

**Comment by dzu181** [comment] 2016-09-19 12:37
This is the first time I install Ubuntu, Sir.
This is also the first time I install ClamTk.

respectfully,
Dzu N




Vào Thứ Hai, ngày 19 tháng 9 năm 2016, Dave M <notifications@github.com> đã
viết:
> This is weird. I have Virtualbox with Ubuntu 16, 15, and 12.04, and this
doesn't happen with any of them. Or Fedora or CentOS either.
>
> Do you remember what version worked last? I'm trying to pinpoint when
something may have happened... may help us figure out what's going on.
>
> respectfully
> Dave M
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/vznLV2ALkPAI57ZC7iE--OuxOG6ahUFc5NVTxmSKCiCZKYEH7EzvOC6So3drAwHA8cYVkNkaZSZgSOJ8s_fDvI0jvK3voTF9M39wzLrl8fyRUjAREIwkS_wl4tRoCMzKVF93K6A8AfUWrtExflEHooqTj-k3Hg=s0-d-e1-ft#https://github.com/notifications/beacon/APwwiSxtOHMvB_C-e9scJdig_ELwwXLQks5qrkxPgaJpZM4J_-ES.gif>

**Comment by dave-theunsub** [comment] 2016-09-19 18:36
Hmmm... this is going to be tough to diagnose then.  Let's try this, although it's a long shot... Open a terminal window and type
sudo apt-get install -f

And see what happens.  Maybe it's missing some dependencies...

respectfully
Dave M

**Comment by dave-theunsub** [comment] 2016-11-02 21:34
Closing for now.  Open a new ticket if you still require assistance.

respectfully
Dave M

**Closed by dave-theunsub** 2016-11-02 21:34 UTC

**Comment by oosterholt** [comment] 2018-01-19 12:31
Found the cause: the ui requires 'double click' on each button to work

**Comment by fisicayquimicaESO** [comment] 2018-04-09 23:40
I was facing the same issue. A quick google search led me to this bug report.

Therefore, I can confirm the issue and the workaround. My suggestion is to change this behaviour unless there is a solid reason to require a double click, as this UI behaviour is quite counter-intuitive.

**Comment by dave-theunsub** [comment] 2018-04-10 06:31
@fisicayquimicaESO You're probably right.  I had some reasons at the time to give an option, but removing it altogether would be better.

Anyway, as soon as I can get a new development system (old one died), I'll add that to the list of stuff for the next version.  :)

Thanks,
Dave M
