### ISSUE TITLE
ClamTk 5.24 scheduler problem on Ubuntu GNOME 17.04

### ISSUE THREAD

**Issue by heynnema** [dave-theunsub/clamtk#82] opened 2017-07-16 03:39 UTC
In Scheduler, Antivirus Signatures, you can't add a time to update signatures, as there's no + icon there to click to save the hours/minutes.

**Comment by dave-theunsub** [comment] 2017-07-16 18:34
Hi,

Yes, that is by design as well. :)  See, several of the big distros include an automatic updater for signatures.  There's no sense doing it twice.  So, if you'd rather update them yourself, use the "Update Assistant" and select "I would like to update sigs myself", and press Apply.  Then you should be able to set a timer for sig updates.

respectfully
Dave M

**Comment by dave-theunsub** [comment] 2019-09-11 16:44
Closing for now.

**Closed by dave-theunsub** 2019-09-11 16:44 UTC
